spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 369123
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  #mpAppId: wx3faf890bc4bb25a3
  mpAppSecret: 2e08a4c297757c74df7bf60856a500bf
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: D:/var/weixin_cert/h5.p12